/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FoodCarat;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author User
 */
public class adminNotification extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    private String cuscreditFile = "resources/customer credit.txt";
    private String userFile = "resources/user.txt";
    /**
     * Creates new form adminNotification
     */
    public adminNotification() {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 204));
        setLocationRelativeTo(null);
        // Initialize the table model and set it to the table
        tableModel = (DefaultTableModel) notificationtable.getModel();
        
        setColumnWidths();
        setRowHeight();
        populateTransactionData();
        
        // Add row selection listener to show receipt on row click
        notificationtable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                showReceipt();
            }
        });
    }
    
     // Method to populate the table with transaction data
    private void populateTransactionData() {
        Admin admin = new Admin();
        ArrayList<String> transactionMessages = admin.getTransactionMessages();

        // Add the transaction messages to the table
        int transactionNumber = 1;
        for (String message : transactionMessages) {
            tableModel.addRow(new Object[]{transactionNumber++, message});
        }
    }

    private void setColumnWidths() {
        TableColumn column = null;
        column = notificationtable.getColumnModel().getColumn(0);
        column.setPreferredWidth(50);

        column = notificationtable.getColumnModel().getColumn(1);
        column.setPreferredWidth(950);
    }

    private void setRowHeight() {
        notificationtable.setRowHeight(30);
    }

    // Show receipt when a row is clicked
    private void showReceipt() {
        int selectedRow = notificationtable.getSelectedRow();
        if (selectedRow != -1) {
            String message = tableModel.getValueAt(selectedRow, 1).toString(); // The message contains the details

            String[] messageParts = message.split(" ");

            // Extract the transaction ID from the message
            String transactionMessageId = messageParts[messageParts.length - 1].replace(")", "").replace(":", "");

            // Retrieve details from the customer credit.txt file
            Admin admin = new Admin();
            String[] customerDetails = admin.performSearch(transactionMessageId, "transactionCredit.txt");
                    
            if (customerDetails != null) {
                // Parse details from the file
                String transID = customerDetails[0];
                String email = customerDetails[1];
                double currentAmount = Double.parseDouble(customerDetails[2]);
                double topUpAmount = Double.parseDouble(customerDetails[3]);
                String datePayment = customerDetails[4];
                String timePayment = customerDetails[5];
                
                // Retrieve name of customer user.txt base on text file
                String [] customerName = admin.performSearch(email, "user.txt");
                String name = customerName[1];
                
                // Create and display the receipt window
                adminCusReceipt receiptWindow = new adminCusReceipt(Integer.parseInt(transID), email, name, currentAmount, topUpAmount, datePayment, timePayment);
                receiptWindow.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Transaction details not found.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        Lnotification = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notificationtable = new javax.swing.JTable();
        backbtn = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lnotification.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        Lnotification.setText("Notification");

        notificationtable.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        notificationtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Messages"
            }
        ));
        jScrollPane1.setViewportView(notificationtable);

        backbtn.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        backbtn.setText("Main Menu");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backbtn)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(455, 455, 455)
                        .addComponent(Lnotification))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1099, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Lnotification)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        this.dispose();
        new adminMain().setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminNotification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lnotification;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable notificationtable;
    // End of variables declaration//GEN-END:variables
}
