/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FoodCarat;

import java.io.IOException;

/**
 *
 * @author User
 */
public class adminTopupCredit extends javax.swing.JFrame {
    private String userFile = "resources/user.txt";
    private String cusFile = "resources/customer.txt";
 
    /**
     * Creates new form adminTopupCredit
     */
    public adminTopupCredit() {
        initComponents();
        topupnumtxt.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                updateSum();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                updateSum();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                updateSum();
            }
        });
        emailtxt.setEditable(false);
        nametxt.setEditable(false);
        currentamounttxt.setEditable(false);
    }
    
    private void clearFields() {
        Admin.clearFields(
            emailtxt, nametxt, currentamounttxt, topupnumtxt, sumtxt
        );
    }
    
    private void updateSum() {
        try {
            // Get the current amount and top-up amount
            String currentAmountStr = currentamounttxt.getText().trim();
            String topUpAmountStr = topupnumtxt.getText().trim();

            // Default values if fields are empty
            double currentAmount = currentAmountStr.isEmpty() ? 0.0 : Double.parseDouble(currentAmountStr);
            double topUpAmount = topUpAmountStr.isEmpty() ? 0.0 : Double.parseDouble(topUpAmountStr);

            // Calculate the new amount
            double newAmount = currentAmount + topUpAmount;

            // Update the sumtxt field
            sumtxt.setText(String.format("%.2f", newAmount));
        } catch (NumberFormatException e) {
            // If the input is invalid, reset the sumtxt field
            sumtxt.setText("Invalid Input");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Lsearch = new javax.swing.JLabel();
        Lemail = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        Lname = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        Lcurrentamount = new javax.swing.JLabel();
        Ltopup = new javax.swing.JLabel();
        Lsum = new javax.swing.JLabel();
        currentamounttxt = new javax.swing.JTextField();
        topupnumtxt = new javax.swing.JTextField();
        sumtxt = new javax.swing.JTextField();
        btopup = new javax.swing.JButton();
        bback = new javax.swing.JButton();
        bsearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabel1.setText("TopUp Credit");

        Lsearch.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        Lsearch.setText("Search:");

        Lemail.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        Lemail.setText("Email:");

        searchtxt.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N

        emailtxt.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });

        Lname.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        Lname.setText("Customer Name:");

        nametxt.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N

        Lcurrentamount.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        Lcurrentamount.setText("Current Amount: ");

        Ltopup.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        Ltopup.setText("Topup Amount:");

        Lsum.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        Lsum.setText("Amount after topup: ");

        currentamounttxt.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N

        topupnumtxt.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N

        sumtxt.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        sumtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumtxtActionPerformed(evt);
            }
        });

        btopup.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        btopup.setText("Top Up");
        btopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btopupActionPerformed(evt);
            }
        });

        bback.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        bback.setText("Back");
        bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbackActionPerformed(evt);
            }
        });

        bsearch.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        bsearch.setText("Search");
        bsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ltopup)
                                    .addComponent(Lcurrentamount)
                                    .addComponent(Lsum))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sumtxt)
                                    .addComponent(currentamounttxt)
                                    .addComponent(topupnumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lemail)
                                    .addComponent(Lsearch))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)
                                        .addComponent(Lname)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btopup)
                        .addGap(248, 248, 248)
                        .addComponent(bback))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel1)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lsearch)
                    .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsearch))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lemail)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lname)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lcurrentamount)
                    .addComponent(currentamounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topupnumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ltopup))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lsum)
                    .addComponent(sumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btopup)
                    .addComponent(bback))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void sumtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumtxtActionPerformed

    private void bsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsearchActionPerformed
        String searchEmail = searchtxt.getText().trim();

        Admin admin = new Admin();
        String[] resultgeneral = admin.performSearch(searchEmail, cusFile);
        String[] resultname = admin.performSearch(searchEmail, userFile);
        // Clear the table and fields before populating
        clearFields();

        if (resultgeneral != null && resultname != null) {
            emailtxt.setText(resultgeneral[0]);
            currentamounttxt.setText(resultgeneral[2]);
            nametxt.setText(resultname[1]);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No matching record found!");
        }
    }//GEN-LAST:event_bsearchActionPerformed

    private void btopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btopupActionPerformed
        try {
            // Get the current amount and top-up amount from the text fields
            String email = emailtxt.getText().trim();
            String name = nametxt.getText().trim();
            String currentAmountStr = currentamounttxt.getText().trim();
            String topUpAmountStr = topupnumtxt.getText().trim();

            if (topUpAmountStr.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter the top-up amount.", "Input Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                topupnumtxt.requestFocus();
                return;
            }

            double currentAmount = Double.parseDouble(currentAmountStr);
            double topUpAmount = Double.parseDouble(topUpAmountStr);

            // Confirm before proceeding
            int option = javax.swing.JOptionPane.showConfirmDialog(this,
                String.format("Name: %s\nTop-up Amount: %.2f\nDo you want to proceed?", name, topUpAmount),
                "Confirm Top-up", javax.swing.JOptionPane.YES_NO_OPTION);

            if (option != javax.swing.JOptionPane.YES_OPTION) {
                return;
            }

            Admin admin = new Admin();
            admin.processTopUp(email, name, currentAmount, topUpAmount);

            clearFields();

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid numbers.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btopupActionPerformed

    private void bbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbackActionPerformed
        this.dispose();
        new adminMain().setVisible(true);
    }//GEN-LAST:event_bbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminTopupCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminTopupCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminTopupCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminTopupCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminTopupCredit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lcurrentamount;
    private javax.swing.JLabel Lemail;
    private javax.swing.JLabel Lname;
    private javax.swing.JLabel Lsearch;
    private javax.swing.JLabel Lsum;
    private javax.swing.JLabel Ltopup;
    private javax.swing.JButton bback;
    private javax.swing.JButton bsearch;
    private javax.swing.JButton btopup;
    private javax.swing.JTextField currentamounttxt;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JTextField sumtxt;
    private javax.swing.JTextField topupnumtxt;
    // End of variables declaration//GEN-END:variables
}
