/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FoodCarat;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class customerPayment extends javax.swing.JFrame {

    /**
     * Creates new form customerPayment
     */
    private int orderID;
    private String orderType;
    
    public customerPayment(int orderID, String orderType) {
        this.orderType = orderType;
        this.orderID = orderID;
        //5,Dine In,[2;2|1;1],Dine In,customerEmail,vendor@mail.com,null
        initComponents();
    }
    
    private void displayOrderDetails() {
        Order order = new Order();
        String orderIDStr = String.valueOf(orderID);
        String[] tokens = order.getOrder(orderIDStr);
        //extract the relevant parameters
        int bookingID = Integer.parseInt(tokens[0]);
        String carID = tokens[1];
        String startDate = tokens[2];
        String endDate = tokens[3];
        double paymentTotalDouble = Double.parseDouble(tokens[5]);
        String paymentTotal = String.format("%.2f", paymentTotalDouble);
        
        //get customer point balance
        Customer customer = new Customer("customerEmail");
        int pointBalance = customer.getPoints();
        int earnablePoints = customer.calculateEarnablePoints(paymentTotalDouble);
        
        //display
        sOrderID.setText(String.valueOf(bookingID));
        sVendorName.setText(String.valueOf(startDate));
        sOrderType.setText(String.valueOf(endDate));
        sDeliveryFee.setText("RM "+String.valueOf(paymentTotal));
        sPayTotal.setText(String.valueOf(earnablePoints));
        //tOrderItem
        sCreditBalance.setText(String.valueOf(pointBalance));
        sPointBalance.setText(String.valueOf(pointBalance));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tOrderItem = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        sOrderID = new javax.swing.JLabel();
        sVendorName = new javax.swing.JLabel();
        sOrderType = new javax.swing.JLabel();
        sDeliveryFee = new javax.swing.JLabel();
        sPayTotal = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tfRedeemPoints = new javax.swing.JSpinner();
        bPay = new javax.swing.JButton();
        bBack = new javax.swing.JButton();
        sCreditBalance = new javax.swing.JLabel();
        sPointBalance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabel1.setText("FoodCarat Food Court");

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel2.setText("Payment");

        jLabel3.setText("Order ID:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Order Summary:");

        jLabel5.setText("Order From:");

        jLabel6.setText("Order Type:");

        jLabel7.setText("Delivery Fee:");

        jLabel8.setText("Payment Total:");

        tOrderItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Unit Price", "Quantity", "Total Price"
            }
        ));
        jScrollPane1.setViewportView(tOrderItem);

        jLabel10.setText("Order Item(s):");

        sOrderID.setText("orderID");

        sVendorName.setText("vendorName");

        sOrderType.setText("orderType");

        sDeliveryFee.setText("deliveryFee");

        sPayTotal.setText("payTotal");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Payment Details:");

        jLabel18.setText("Credit Balance:");

        jLabel19.setText("Point Balance:");

        jLabel20.setText("Redeem Points:");

        bPay.setText("Pay");
        bPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPayActionPerformed(evt);
            }
        });

        bBack.setText("Back to Cart");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });

        sCreditBalance.setText("creaditBalance");

        sPointBalance.setText("pointBalance");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sOrderID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sVendorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sOrderType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(29, 29, 29)
                                        .addComponent(sDeliveryFee))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(sPayTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sCreditBalance)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sPointBalance)
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bPay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bBack, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(82, 82, 82)
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfRedeemPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sOrderID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sVendorName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(sOrderType)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(sDeliveryFee))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(sPayTotal))
                        .addGap(22, 22, 22)))
                .addGap(7, 7, 7)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(sCreditBalance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tfRedeemPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(sPointBalance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPay)
                    .addComponent(bBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPayActionPerformed
        Calendar today = Calendar.getInstance();

        try (BufferedReader br = new BufferedReader(new FileReader("resources/customerOrder.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] tokens = line.split(",");
                int cusOrderID = Integer.parseInt(tokens[0]);

                if (cusOrderID == Integer.parseInt(sOrderID.getText())) { 
                    //5,Dine In,[2;2|1;1],Dine In,customerEmail,vendor@mail.com,null
                    double paymentTotal = Double.parseDouble(tokens[5]);

                    //check if points redemption is within the valid range
                    int redeemPoints = (int) tfRedeemPoints.getValue(); //user wants to redeem
                    int currentPoints = Integer.parseInt(sPointBalance.getText()); //user's current point balance

                    if (redeemPoints > currentPoints) {
                        JOptionPane.showMessageDialog(rootPane, "Points to redeem exceeds current balance.");
                        return; 
                    } else if (redeemPoints < 0) {
                        JOptionPane.showMessageDialog(rootPane, "Points to redeem cannot be negative.");
                        return;
                    }

                    double newPaymentTotal = paymentTotal - redeemPoints; 

                    Customer customer = new Customer(UserSession.getUsername());
                    customer.deductPoints(redeemPoints);

                    Booking booking = new Booking(bookingID, carID, startDate, endDate);
                    booking.writeBookingDetails(cardNum, newPaymentTotal, bookingID); //write order date

                    JOptionPane.showMessageDialog(rootPane, "Payment successful.");
                    dispose();
                    customerReceipt frame = new customerReceipt(bookingID);
                    frame.setVisible(true);
                    return; 
                }
            }
            JOptionPane.showMessageDialog(rootPane, "No matching booking found.");
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "An error occurred while saving payment details.");
        }
    }//GEN-LAST:event_bPayActionPerformed

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        this.dispose();
        customerViewMenu frame = new customerViewMenu(orderID, orderType);
        frame.setVisible(true);
    }//GEN-LAST:event_bBackActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBack;
    private javax.swing.JButton bPay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sCreditBalance;
    private javax.swing.JLabel sDeliveryFee;
    private javax.swing.JLabel sOrderID;
    private javax.swing.JLabel sOrderType;
    private javax.swing.JLabel sPayTotal;
    private javax.swing.JLabel sPointBalance;
    private javax.swing.JLabel sVendorName;
    private javax.swing.JTable tOrderItem;
    private javax.swing.JSpinner tfRedeemPoints;
    // End of variables declaration//GEN-END:variables
}
