/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FoodCarat;

import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

public class customerReceipt extends javax.swing.JFrame {

    /**
     * Creates new form customerReceipt
     */
    private int orderID;
    private String orderType;
    DecimalFormat df = new DecimalFormat("0.00");

    public customerReceipt(int orderID, String orderType) {
        this.orderType = orderType.toLowerCase();
        this.orderID = orderID;
        initComponents();
        displayOrderDetails();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(180, 200, 234));
    }

    private void displayOrderDetails() {
        Order order = new Order(orderType, User.getSessionEmail());
        String[] tokens = order.getOrder(orderID); // This might throw IOException
        //Extract the relevant parameters
        String orderType = tokens[1];
        String orderItems = tokens[2];
        String deliveryFee = tokens[7];
        String paidTotal = tokens[8];
        String orderDate = tokens[9];
        User user = new User(User.getSessionEmail());
        String[] userInfo = user.getUserInfo(User.getSessionEmail());
        String userContact = userInfo[5];

        String formattedOrderType = "";
        switch (this.orderType) {
            case "dine in":
                formattedOrderType = "Dine In";
                break;
            case "take away":
                formattedOrderType = "Take Away";
                break;
            case "delivery":
                formattedOrderType = "Delivery";
                break;
            default:
                formattedOrderType = "Unknown"; //invalid value
        }

        //Display
        sOrderID.setText(String.valueOf(orderID));
        sOrderDate.setText(orderDate);
        sUsername.setText(User.getSessionName());
        sHPNum.setText(userContact);
        sOrderType.setText(formattedOrderType);
        //calculate redeemed points here
        double deliveryFeeDouble = Double.parseDouble(deliveryFee.replace("RM ", ""));
        double paidTotalDouble = Double.parseDouble(paidTotal.replace("RM ", ""));
        double subtotal = populateOrderItemsTable(orderItems);
        double subtotalAfterRedeem = paidTotalDouble - deliveryFeeDouble;
        double redeemedAmount = subtotal - subtotalAfterRedeem;
        double redeemedPoints = redeemedAmount / 0.01;
        //display the values
        sDeliveryFee.setText("RM " + String.format("%.2f", deliveryFeeDouble));
        sPayTotal.setText("RM " + String.format("%.2f", paidTotalDouble));
        sRedeemedPoint.setText(String.format("%.0f", redeemedPoints));
    }

    private double populateOrderItemsTable(String orderItemsString) { //to set the order table, vendor name and calculate subtotal
        DefaultTableModel model = (DefaultTableModel) tOrderItem.getModel();
        model.setRowCount(0);  //clear table
        double subtotal = 0.0; //for subtotal calculation

        //retrieve the order item
        orderItemsString = orderItemsString.replace("[", "").replace("]", "");
        String[] items = orderItemsString.split("\\|");

        // Loop through each item and add it to the table
        for (String item : items) {
            // Split each item by the semicolon to get itemID and quantity
            String[] itemDetails = item.split(";");
            if (itemDetails.length == 2) {
                int itemID = Integer.parseInt(itemDetails[0]);
                String quantity = itemDetails[1];

                Item item1 = new Item();
                String[] itemData = item1.itemData(itemID);
                String itemName = itemData[1];
                double itemPrice = Double.parseDouble(itemData[3]);
                double orderItemTotal = Integer.parseInt(quantity) * itemPrice;
                subtotal += orderItemTotal;

                String[] vendorInfo = item1.getVendorInfoByItemID(itemID);
                String vendorName = vendorInfo[1];
                sVendorName.setText(String.valueOf(vendorName));

                // Add the item to the table
                model.addRow(new Object[]{itemName, "RM " + df.format(itemPrice), quantity, "RM " + df.format(orderItemTotal)});
            }
        }
        sSubTotal.setText("RM " + String.format("%.2f", subtotal));
        return subtotal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tOrderItem = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bBack = new javax.swing.JButton();
        sOrderID = new javax.swing.JLabel();
        sOrderDate = new javax.swing.JLabel();
        sUsername = new javax.swing.JLabel();
        sHPNum = new javax.swing.JLabel();
        sVendorName = new javax.swing.JLabel();
        sOrderType = new javax.swing.JLabel();
        sSubTotal = new javax.swing.JLabel();
        sRedeemedPoint = new javax.swing.JLabel();
        sPayTotal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sDeliveryFee = new javax.swing.JLabel();
        bOrderHistory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabel1.setText("FoodCarat Food Court");

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel2.setText("Order Receipt");

        jLabel3.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel3.setText("Order ID:");

        jLabel4.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel4.setText("Order Date:");

        jLabel5.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel5.setText("Order From:");

        jLabel6.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel6.setText("Order Type:");

        jLabel7.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel7.setText("Order Item(s):");

        tOrderItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Unit Price", "Quantity", "Total Price"
            }
        ));
        tOrderItem.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tOrderItem);

        jLabel8.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel8.setText("Payment Details");

        jLabel9.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel9.setText("Customer Name:");

        jLabel10.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel10.setText("Customer Contact:");

        jLabel11.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel11.setText("Order Details");

        jLabel12.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel12.setText("Subtotal:");

        jLabel13.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel13.setText("Points Redeemed:");

        jLabel14.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel14.setText("Total Payment:");

        bBack.setText("Main Menu");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });

        sOrderID.setText("orderID");

        sOrderDate.setText("orderDate");

        sUsername.setText("cusName");

        sHPNum.setText("cusContact");

        sVendorName.setText("vendorName");

        sOrderType.setText("orderType");

        sSubTotal.setText("subTotal");

        sRedeemedPoint.setText("pointRedeem");

        sPayTotal.setText("payTotal");

        jLabel15.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel15.setText("Delivery Fee:");

        sDeliveryFee.setText("deliveryFee");

        bOrderHistory.setText("Order History");
        bOrderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrderHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bOrderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bBack, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel8)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7))
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sOrderID)
                                .addComponent(sOrderDate)
                                .addComponent(sUsername)
                                .addComponent(sHPNum)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sVendorName)
                                    .addGap(86, 86, 86)
                                    .addComponent(jLabel6)
                                    .addGap(32, 32, 32)
                                    .addComponent(sOrderType))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel12)
                                .addComponent(jLabel15))
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sPayTotal)
                                .addComponent(sRedeemedPoint)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(sDeliveryFee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sSubTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBack)
                    .addComponent(bOrderHistory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sOrderID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sOrderDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sHPNum))
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(sVendorName)
                    .addComponent(sOrderType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(sSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(sDeliveryFee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(sRedeemedPoint))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(sPayTotal))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        this.dispose();
        customerMain frame = new customerMain();
        frame.setVisible(true);
    }//GEN-LAST:event_bBackActionPerformed

    private void bOrderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrderHistoryActionPerformed
        this.dispose();
        customerOrderHistory frame = new customerOrderHistory();
        frame.setVisible(true);
    }//GEN-LAST:event_bOrderHistoryActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBack;
    private javax.swing.JButton bOrderHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sDeliveryFee;
    private javax.swing.JLabel sHPNum;
    private javax.swing.JLabel sOrderDate;
    private javax.swing.JLabel sOrderID;
    private javax.swing.JLabel sOrderType;
    private javax.swing.JLabel sPayTotal;
    private javax.swing.JLabel sRedeemedPoint;
    private javax.swing.JLabel sSubTotal;
    private javax.swing.JLabel sUsername;
    private javax.swing.JLabel sVendorName;
    private javax.swing.JTable tOrderItem;
    // End of variables declaration//GEN-END:variables
}
