/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FoodCarat;

import java.awt.Image;
import java.io.File;
import java.text.DecimalFormat;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author mastu
 */
public class vendorMain extends javax.swing.JFrame {

    /**
     * Creates new form vendorMain
     */
    
    //change to userSession 
    private String email = "vendor@mail.com";
    private String name = "Vendor";
//    private String email = User.getSessionEmail();
//    private String name = User.getSessionName();
    Vendor vendor = new Vendor(email);
    
    public vendorMain() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(186,85,211)); //setting background color of frame
        setLocationRelativeTo(null);
        
        //display vendor info
        displayInfo();
    }
        
    public void displayInfo() { //display vendor info
        if (vendor != null) {
            salutationTxt.setText(name);
            emailTxt.setText(email);
            nameTxt.setText(name);
            cuisineTxt.setText(vendor.getCuisine());
            
            DecimalFormat df = new DecimalFormat("0.00");
            String credit = df.format(vendor.getCreditBalance());
            creditTxt.setText("RM"+credit); 
            
            ImageIcon icon = new ImageIcon(vendor.getPhotoLink());
            Image img = icon.getImage();
            Image resizedImage = img.getScaledInstance(vendorLogo.getWidth(), vendorLogo.getHeight(), Image.SCALE_SMOOTH);
            vendorLogo.setIcon(new ImageIcon(resizedImage));
            
            displayMethod();
        } else {
            JOptionPane.showMessageDialog(this, "Vendor information not found for email: " + email,
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    //display available method
    public void displayMethod() {
        String methods = vendor.getAvailableMethod();
        methods = methods.substring(1, methods.length() - 1); //remove the square brackets
        String[] methodList = methods.split(";");
        //display checkboxes based on method saved
        dineInBox.setSelected(Arrays.asList(methodList).contains("Dine In"));
        takeawayBox.setSelected(Arrays.asList(methodList).contains("Take Away"));
        deliveryBox.setSelected(Arrays.asList(methodList).contains("Delivery"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        itemBtn = new javax.swing.JButton();
        notificationBtn = new javax.swing.JButton();
        currentOrderBtn = new javax.swing.JButton();
        reviewBtn = new javax.swing.JButton();
        revenueBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        orderHistoryBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        salutationTxt = new javax.swing.JLabel();
        vendorLogo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JLabel();
        nameTxt = new javax.swing.JLabel();
        cuisineTxt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        creditTxt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        dineInBox = new javax.swing.JCheckBox();
        takeawayBox = new javax.swing.JCheckBox();
        deliveryBox = new javax.swing.JCheckBox();
        updateMethodBtn = new javax.swing.JButton();
        openAllBtn = new javax.swing.JButton();
        closeAllBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 102, 255));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabel1.setText("Vendor Main Menu");

        itemBtn.setText("Menu Item");
        itemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBtnActionPerformed(evt);
            }
        });

        notificationBtn.setText("Notifications");
        notificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationBtnActionPerformed(evt);
            }
        });

        currentOrderBtn.setText("Current Orders");
        currentOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentOrderBtnActionPerformed(evt);
            }
        });

        reviewBtn.setText("Reviews");
        reviewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewBtnActionPerformed(evt);
            }
        });

        revenueBtn.setText("Revenue");
        revenueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenueBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        orderHistoryBtn.setText("Order History");
        orderHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderHistoryBtnActionPerformed(evt);
            }
        });

        salutationTxt.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        salutationTxt.setText("Welcome, Vendor");

        vendorLogo.setText("Profile Pic");

        jLabel3.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel3.setText("Vendor Name:");

        jLabel4.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel4.setText("Vendor Email:");

        jLabel5.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel5.setText("Vendor Cuisine:");

        emailTxt.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        emailTxt.setText("mail@mail.com");

        nameTxt.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        nameTxt.setText("vendor");

        cuisineTxt.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        cuisineTxt.setText("cuisine");

        jLabel6.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel6.setText("**To update vendor information, please approach the admin for update.");

        jLabel7.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel7.setText("Current Balance:");

        creditTxt.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        creditTxt.setText("RM0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cuisineTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(emailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(nameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(salutationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vendorLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(creditTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salutationTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vendorLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(emailTxt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameTxt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cuisineTxt))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(creditTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setForeground(new java.awt.Color(228, 204, 255));

        jLabel.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel.setText("Order Method Availability");

        dineInBox.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        dineInBox.setText("Dine In");

        takeawayBox.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        takeawayBox.setText("Take Away");

        deliveryBox.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        deliveryBox.setText("Delivery");

        updateMethodBtn.setText("Update Methods");
        updateMethodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMethodBtnActionPerformed(evt);
            }
        });

        openAllBtn.setText("Open All Methods");
        openAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAllBtnActionPerformed(evt);
            }
        });

        closeAllBtn.setText("Close All Methods");
        closeAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAllBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deliveryBox)
                            .addComponent(takeawayBox)
                            .addComponent(dineInBox))
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(closeAllBtn)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(updateMethodBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(openAllBtn))
                                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel)
                .addGap(27, 27, 27)
                .addComponent(dineInBox)
                .addGap(18, 18, 18)
                .addComponent(takeawayBox)
                .addGap(18, 18, 18)
                .addComponent(deliveryBox)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateMethodBtn)
                    .addComponent(openAllBtn))
                .addGap(28, 28, 28)
                .addComponent(closeAllBtn)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reviewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(revenueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notificationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(343, 343, 343))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(notificationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(currentOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(orderHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(reviewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(revenueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(logoutBtn))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {logoutBtn, revenueBtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBtnActionPerformed
        new vendorMenu().setVisible(true);
        dispose();        
    }//GEN-LAST:event_itemBtnActionPerformed

    private void notificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationBtnActionPerformed
        new vendorNotification().setVisible(true);
        dispose();  
    }//GEN-LAST:event_notificationBtnActionPerformed

    private void currentOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentOrderBtnActionPerformed
        new vendorCurrentOrder().setVisible(true);
        dispose();  
    }//GEN-LAST:event_currentOrderBtnActionPerformed

    private void reviewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewBtnActionPerformed
        new vendorReview().setVisible(true);
        dispose();  
    }//GEN-LAST:event_reviewBtnActionPerformed

    private void revenueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenueBtnActionPerformed
        new vendorRevenue().setVisible(true);
        dispose();  
    }//GEN-LAST:event_revenueBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        User.clearSession();
        dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void orderHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderHistoryBtnActionPerformed
        new vendorOrderHistory().setVisible(true);
        dispose(); 
    }//GEN-LAST:event_orderHistoryBtnActionPerformed

    private void updateMethodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMethodBtnActionPerformed
        //see which is ticked, rewrite in the text file for the available methods, save as array
        String[] selectedMethod = new String[3];
        int index = 0;
        String methodString = "";
        
        //check if checkbox is ticked
        if (!dineInBox.isSelected() && !deliveryBox.isSelected() && !deliveryBox.isSelected()) {
            int confirm = JOptionPane.showConfirmDialog(null, "Close all methods?", "Close All Methods", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                methodString = "[]";
            }
        } else {
            if (dineInBox.isSelected()) {
                selectedMethod[index++] = "Dine In";
            }
            if (takeawayBox.isSelected()) {
                selectedMethod[index++] = "Take Away";
            }
            if (deliveryBox.isSelected()) {
                selectedMethod[index++] = "Delivery";
            }

            selectedMethod = Arrays.copyOf(selectedMethod, index); //adjust the size of array
            methodString = "[" + String.join(";", selectedMethod) + "]";
        }
        //call method to update method from vendor class
        vendor.updateMethodAvailable(methodString);
        vendor.setAvailableMethod(methodString); //set current session's available methods
        displayInfo(); //refresh info
    }//GEN-LAST:event_updateMethodBtnActionPerformed

    private void openAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAllBtnActionPerformed
        //add all methods
        int confirm = JOptionPane.showConfirmDialog(null, "Open all methods?", "Open All Methods", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String methodString = "[Dine In;Take Away;Delivery]";
            vendor.updateMethodAvailable(methodString);
            vendor.setAvailableMethod(methodString);
            displayInfo(); //refresh info
        }
    }//GEN-LAST:event_openAllBtnActionPerformed

    private void closeAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAllBtnActionPerformed
        //rewrite [] into methods for vendor
        int confirm = JOptionPane.showConfirmDialog(null, "Close all methods?", "Close All Methods", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String methodString = "[]";
            vendor.updateMethodAvailable(methodString);
            vendor.setAvailableMethod(methodString);
            displayInfo(); //refresh info
        }
    }//GEN-LAST:event_closeAllBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vendorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vendorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vendorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vendorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vendorMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeAllBtn;
    private javax.swing.JLabel creditTxt;
    private javax.swing.JLabel cuisineTxt;
    private javax.swing.JButton currentOrderBtn;
    private javax.swing.JCheckBox deliveryBox;
    private javax.swing.JCheckBox dineInBox;
    private javax.swing.JLabel emailTxt;
    private javax.swing.JButton itemBtn;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel nameTxt;
    private javax.swing.JButton notificationBtn;
    private javax.swing.JButton openAllBtn;
    private javax.swing.JButton orderHistoryBtn;
    private javax.swing.JButton revenueBtn;
    private javax.swing.JButton reviewBtn;
    private javax.swing.JLabel salutationTxt;
    private javax.swing.JCheckBox takeawayBox;
    private javax.swing.JButton updateMethodBtn;
    private javax.swing.JLabel vendorLogo;
    // End of variables declaration//GEN-END:variables
}
